Add intervalMs option for flexible local notification scheduling
Android only option for scheduleLocalNotificationAsync function that enables users to set repeat interval of local notifications to any number of milliseconds.

**Use case**: I need to schedule notifications with a interval of user defined days or hours. Current API enables me to schedule local notification every one hour, or every one day. There is no option to schedule every 5 hours for example. More info here https://forums.expo.io/t/flexible-repeat-for-local-notification-scheduling/1441

This change enables users to set repeat interval in milliseconds for maximum flexibility.

**Added code is completely covered by unit tests.**

I will also make a pull request to the expo client project with this small commit that enables this change:
https://github.com/lvojnovic/expo/commit/77b0f26ee0d2d78c7d9c626c2a612f030761446a

Unfortunately, I was not able to setup my local expo client with local expo-sdk. Client would not start in the simulator (Kernel manifest invalid. Make sure [exp] Making sure project is set up correctly... is running inside of exponent/js/__internal__ and rebuild the app) even though I had [exp] Making sure project is set up correctly... running in the js folder. There is no __internal__ folder. When I tried __develop__ folder I got  after cloning expo-dev/react-native-lab. I also tried running expo-dev following the instructions in the README. It also failed to run tools/setup (Error: Cannot find module '\''/Users/{MYUSER}/workspace/expo-dev/react-native-lab/react-native/local-cli/core/rn-cli.config.js'\'').

Closes expo/expo-sdk#75

fbshipit-source-id: 5c0d681